version: '3.9'
services:
  db:
    image: library/postgres:11.11
    ports:
      - 5432:5432
    volumes: # here is where you could persist data even if container shuts down
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=unicorn
      - PGDATA=/var/lib/postgresql/data/pgdata
  api:
    build: .
    ports:
      - 8027:8080
    volumes:
      - .:/app