version: '3.9'
services:
  db:
    image: library/postgres:11.11
    container_name: compound_poem_database
    ports:
      - 5432:5432
    volumes: # here is where you could persist data even if container shuts down
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=unicorn
      - PGDATA=/var/lib/postgresql/data/pgdata
  api:
    build: .
    container_name: compound_poem_application
    ports:
      - 8001:8080
    volumes:
      - .:/app
    command:
      sbt compound_poem_app/run
#    frontend:
#      build: .
#      container_name: frontend
#      ports:
#        - 8002:8080
#      volumes:
#        - .:/app
#      command:
#        ???
volumes:
  pgdata: