--CREATE DATABASE unicorn_test;
--GRANT ALL PRIVILEGES ON unicorn_test TO root;

--CREATE SCHEMA QA; --default is public
--GRANT ALL ON SCHEMA QA TO root;
--CREATE TABLE Persons (
--    PersonID int,
--    LastName varchar(255),
--    FirstName varchar(255),
--    Address varchar(255),
--    City varchar(255)
--);
--GRANT ALL ON SCHEMA public TO root;